language: php
php:
  - '5.6'
  - '7.0'
services:
  - docker
install:

  # Install composer deps
  - composer install

script:

  # Run code and styling
  - composer test

after_success:
  - echo "Deploy here"
